"use client";

import { useState } from "react";
import { ArrowRight, LockKeyhole, PhoneCall } from "lucide-react";
import { createClient, isDemoModeAllowed, isSupabaseConfigured } from "@/lib/supabase/client";

export default function LoginPage(){
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");if(!isSupabaseConfigured){if(isDemoModeAllowed){location.href="/dashboard";return}setError("本番環境のSupabase接続が未設定です。環境変数を確認してください。");setBusy(false);return}const {error}=await createClient().auth.signInWithPassword({email,password});if(error){setError("メールアドレスまたはパスワードが正しくありません");setBusy(false);return}location.href="/dashboard"};
 return <main className="grid min-h-screen lg:grid-cols-2"><section className="hidden bg-[#111a2e] p-16 text-white lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3 text-xl font-extrabold"><span className="grid size-10 place-items-center rounded-xl bg-gradient-to-br from-blue-400 to-violet-600 text-sm">CF</span>CallFlow</div><div><div className="mb-6 grid size-16 place-items-center rounded-2xl bg-blue-500/15"><PhoneCall className="size-8 text-blue-400"/></div><h1 className="max-w-lg text-4xl font-extrabold leading-tight">架電からアポ獲得まで、<br/>チームの動きをひとつに。</h1><p className="mt-5 max-w-md text-sm leading-7 text-slate-400">企業リスト、通話記録、AI要約、フォロー予定、チーム実績を一元管理するテレアポ専用CRM。</p></div><p className="text-[10px] text-slate-600">© 2026 CallFlow CRM</p></section><section className="grid place-items-center p-6"><form onSubmit={submit} className="w-full max-w-sm"><div className="mb-8 lg:hidden"><b className="text-xl">CallFlow</b></div><p className="text-xs font-bold text-blue-600">WELCOME BACK</p><h2 className="mt-2 text-3xl font-extrabold">ログイン</h2><p className="mt-2 text-sm text-slate-500">営業チームのワークスペースへ</p><label className="mt-8 block text-xs font-bold">メールアドレス<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} className="input mt-2" placeholder="name@company.jp"/></label><label className="mt-4 block text-xs font-bold">パスワード<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} className="input mt-2" placeholder="8文字以上"/></label>{error&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-xs text-red-600">{error}</p>}<button disabled={busy||(!isSupabaseConfigured&&!isDemoModeAllowed)} className="btn btn-primary mt-6 w-full py-3 disabled:opacity-50">{isSupabaseConfigured?(busy?"ログイン中…":"ログインする"):isDemoModeAllowed?"デモ版を開く":"Supabase設定が必要です"}<ArrowRight size={15}/></button>{!isSupabaseConfigured&&<p className={`mt-3 text-center text-[10px] ${isDemoModeAllowed?"text-amber-700":"text-red-600"}`}><LockKeyhole className="mr-1 inline size-3"/>{isDemoModeAllowed?"現在はデモモードです。入力内容はこのブラウザだけに保存されます。":"本番モードです。Vercelの環境変数にSupabase URLとキーを設定してください。"}</p>}</form></section></main>
}
