"use client";

import { useEffect, useMemo, useState } from "react";
import { Building2, ChevronRight, ExternalLink, History, LayoutDashboard, LogOut, Menu, Phone, Plus, Search, Sparkles, Upload, Users, X } from "lucide-react";
import { loadCRMData, saveCallLog, saveCompany } from "@/lib/data";
import { isSupabaseConfigured, createClient } from "@/lib/supabase/client";
import type { CallLog, CallResult, Company, Heat, TranscriptAnalysis } from "@/lib/types";

type View = "dashboard" | "call" | "companies" | "history" | "team";
const members = ["辻 保", "山田 花子", "佐藤 健", "高橋 美咲"];
const results: { value: CallResult; label: string }[] = [
  { value:"アポ獲得", label:"◎ アポ獲得" }, { value:"資料送付", label:"▣ 資料送付" },
  { value:"再架電", label:"↻ 再架電" }, { value:"担当者不在", label:"◷ 担当者不在" },
  { value:"見込みなし", label:"× 見込みなし" }, { value:"その他", label:"… その他" },
];
const meta: Record<View, [string,string]> = {
  dashboard:["ダッシュボード","今日の架電状況を確認できます"], call:["架電する","企業情報を確認しながら記録できます"],
  companies:["企業リスト","見込み顧客を検索・管理できます"], history:["架電履歴","チーム全体の活動履歴"], team:["メンバー・実績","担当者別の活動を確認できます"],
};
const fmt = (v?: string, time = false) => v ? new Intl.DateTimeFormat("ja-JP", { month:"numeric", day:"numeric", ...(time ? { hour:"2-digit", minute:"2-digit" } : {}) }).format(new Date(v)) : "未設定";
const badge = (result: string) => result === "アポ獲得" ? "bg-emerald-50 text-emerald-700" : result === "資料送付" ? "bg-purple-50 text-purple-700" : result === "見込みなし" ? "bg-red-50 text-red-600" : "bg-amber-50 text-amber-700";

export default function CallFlowApp() {
  const [view,setView] = useState<View>("dashboard");
  const [companies,setCompanies] = useState<Company[]>([]);
  const [logs,setLogs] = useState<CallLog[]>([]);
  const [loading,setLoading] = useState(true);
  const [callIndex,setCallIndex] = useState(0);
  const [member,setMember] = useState("辻 保");
  const [teamMembers,setTeamMembers] = useState(members);
  const [menu,setMenu] = useState(false);
  const [companyModal,setCompanyModal] = useState(false);
  const [importModal,setImportModal] = useState(false);
  const [aiModal,setAiModal] = useState(false);
  const [toast,setToast] = useState("");

  const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(""),2600)};
  const refresh = async () => { try { const data=await loadCRMData(); setCompanies(data.companies); setLogs(data.logs);setTeamMembers(data.members);setMember(data.currentUser); } catch(e) { notify(e instanceof Error?e.message:"データの取得に失敗しました"); } finally { setLoading(false); } };
  useEffect(()=>{let active=true;loadCRMData().then(data=>{if(active){setCompanies(data.companies);setLogs(data.logs);setTeamMembers(data.members);setMember(data.currentUser)}}).catch(e=>{if(active)setToast(e instanceof Error?e.message:"データの取得に失敗しました")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const go=(next:View)=>{setView(next);setMenu(false)};
  const callCompany=(company:Company)=>{setCallIndex(Math.max(0,companies.findIndex(c=>c.id===company.id)));go("call")};
  const logout=async()=>{if(isSupabaseConfigured)await createClient().auth.signOut();location.href="/login"};

  return <div className="min-h-screen bg-[#f5f7fb] text-[#172036]">
    <aside className={`fixed inset-y-0 left-0 z-40 w-[238px] bg-[#111a2e] px-[18px] py-6 text-white transition-transform lg:translate-x-0 ${menu?"translate-x-0":"-translate-x-full"}`}>
      <div className="mb-8 flex items-center gap-2.5 px-2 text-xl font-extrabold"><span className="grid size-8 place-items-center rounded-[9px] bg-gradient-to-br from-blue-400 to-violet-600 text-xs">CF</span><span>CallFlow<small className="block text-[8px] tracking-[1.7px] text-slate-500">TELESALES CRM</small></span></div>
      <Nav view={view} go={go}/>
      <div className="absolute bottom-5 left-[18px] right-[18px] border-t border-slate-700 pt-4">
        <div className="flex items-center gap-2.5"><div className="grid size-9 place-items-center rounded-full bg-blue-500 text-xs font-bold">辻</div><div className="min-w-0 flex-1"><b className="block text-xs">辻 保</b><span className="text-[10px] text-slate-500">管理者</span></div><button onClick={logout} aria-label="ログアウト"><LogOut size={15} className="text-slate-500"/></button></div>
      </div>
    </aside>
    {menu&&<button className="fixed inset-0 z-30 bg-slate-950/50 lg:hidden" onClick={()=>setMenu(false)} aria-label="メニューを閉じる"/>}
    <main className="min-h-screen lg:ml-[238px]">
      <header className="flex min-h-[76px] items-center justify-between gap-3 px-4 md:px-8"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={()=>setMenu(true)}><Menu/></button><div><h1 className="text-xl font-extrabold tracking-tight md:text-2xl">{meta[view][0]}</h1><p className="mt-1 hidden text-xs text-slate-500 sm:block">{meta[view][1]}</p></div></div><div className="flex gap-2"><select disabled={isSupabaseConfigured} className="input hidden !w-auto disabled:bg-slate-50 md:block" value={member} onChange={e=>setMember(e.target.value)}>{teamMembers.map(m=><option key={m}>{m}</option>)}</select><button className="btn btn-ai" onClick={()=>setAiModal(true)}><Sparkles size={15}/><span className="hidden sm:inline">文字起こし解析</span></button></div></header>
      <div className="px-4 pb-10 md:px-8">{loading?<Loading/>:<>
        {view==="dashboard"&&<Dashboard companies={companies} logs={logs} go={go}/>} 
        {view==="companies"&&<Companies companies={companies} callCompany={callCompany} add={()=>setCompanyModal(true)} bulkImport={()=>setImportModal(true)}/>} 
        {view==="call"&&<CallScreen company={companies[callIndex]} member={member} next={()=>setCallIndex(i=>(i+1)%companies.length)} onSaved={refresh} notify={notify}/>} 
        {view==="history"&&<HistoryView logs={logs}/>} 
        {view==="team"&&<Team logs={logs} members={teamMembers}/>} 
      </>}</div>
    </main>
    {companyModal&&<CompanyModal member={member} close={()=>setCompanyModal(false)} saved={async c=>{setCompanies(x=>[c,...x]);setCompanyModal(false);notify("企業を登録しました")}}/>}
    {importModal&&<LeadImportModal member={member} existing={companies} close={()=>setImportModal(false)} saved={async added=>{await refresh();setImportModal(false);notify(`${added}件の営業先を取り込みました`)}}/>}
    {aiModal&&<TranscriptModal company={companies[callIndex]} close={()=>setAiModal(false)} onApply={(a,transcript)=>{sessionStorage.setItem("callflow_analysis",JSON.stringify({...a,transcript}));setAiModal(false);go("call");notify("解析結果を架電記録へ反映しました")}}/>}
    {toast&&<div className="fixed bottom-6 right-6 z-[70] rounded-xl bg-[#152039] px-5 py-3 text-sm font-semibold text-white shadow-2xl">{toast}</div>}
    {!isSupabaseConfigured&&<div className="fixed bottom-3 left-3 z-20 rounded-full bg-amber-100 px-3 py-1 text-[10px] font-bold text-amber-800 lg:left-[250px]">デモモード</div>}
  </div>;
}

function Nav({view,go}:{view:View;go:(v:View)=>void}) { const items:[View,string,React.ReactNode][]=[["dashboard","ダッシュボード",<LayoutDashboard key="a"/>],["call","架電する",<Phone key="b"/>],["companies","企業リスト",<Building2 key="c"/>],["history","架電履歴",<History key="d"/>],["team","メンバー・実績",<Users key="e"/>]];return <nav><p className="mb-2 px-3 text-[9px] font-bold tracking-[1.5px] text-slate-600">メイン</p>{items.map(([id,label,icon],i)=><button key={id} onClick={()=>go(id)} className={`mb-1 flex w-full items-center gap-3 rounded-[9px] px-3 py-2.5 text-left text-[13px] ${view===id?"bg-[#1d2943] text-white":"text-slate-400 hover:bg-[#1d2943] hover:text-white"} ${i===4?"mt-6":""}`}>{<span className="[&>svg]:size-4">{icon}</span>}{label}</button>)}</nav> }
function Loading(){return <div className="grid min-h-[60vh] place-items-center"><div className="text-center"><div className="mx-auto mb-3 size-8 animate-spin rounded-full border-4 border-blue-100 border-t-blue-600"/><p className="text-xs text-slate-500">データを読み込んでいます</p></div></div>}

function Dashboard({companies,logs,go}:{companies:Company[];logs:CallLog[];go:(v:View)=>void}) {
 const today=new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo"}).format(new Date()), todayLogs=logs.filter(l=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo"}).format(new Date(l.created_at))===today);const calls=todayLogs.length||(isSupabaseConfigured?0:38),appt=todayLogs.filter(l=>l.result==="アポ獲得").length||(isSupabaseConfigured?0:3),materials=todayLogs.filter(l=>l.result==="資料送付").length||(isSupabaseConfigured?0:5),follow=companies.filter(c=>c.next_action_at).length;
 const kpis=[["本日の架電数",calls,"目標 50件"],["接続数",Math.max(1,Math.round(calls*.45)),"接続率 44.7%"],["アポ獲得",appt,"前日比 +1"],["資料送付",materials,"送付待ち 2件"],["要フォロー",follow,"期限順に表示"]];
 return <div className="fade-in"><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-5">{kpis.map(([l,v,s])=><div className="card p-4" key={l}><p className="text-[11px] font-bold text-slate-500">{l}</p><p className="my-1 text-[27px] font-extrabold">{v}</p><p className="text-[10px] text-emerald-600">{s}</p></div>)}</div><div className="mt-4 grid gap-4 xl:grid-cols-[1.55fr_1fr]"><div className="card"><CardHead title="直近7日間の活動" sub="チーム全体"/><div className="p-5"><ActivityChart logs={logs}/></div></div><div className="card"><CardHead title="フォロー予定" sub="すべて見る" click={()=>go("companies")}/><div className="p-4">{companies.filter(c=>c.next_action_at).slice(0,5).map(c=><div key={c.id} className="flex items-center gap-3 border-b border-slate-100 py-2.5 last:border-0"><div className="grid size-10 place-items-center rounded-lg bg-blue-50 text-[11px] font-extrabold text-blue-600">{fmt(c.next_action_at)}</div><div className="min-w-0 flex-1"><b className="block truncate text-xs">{c.name}</b><span className="text-[10px] text-slate-500">{fmt(c.next_action_at,true)}・{c.owner_name}</span></div><HeatBadge heat={c.heat}/></div>)}</div></div></div></div>
}
function ActivityChart({logs}:{logs:CallLog[]}){const formatter=new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo"});const data=Array.from({length:7},(_,i)=>{const date=new Date();date.setDate(date.getDate()-(6-i));const key=formatter.format(date),items=logs.filter(l=>formatter.format(new Date(l.created_at))===key);return [new Intl.DateTimeFormat("ja-JP",{weekday:"short",timeZone:"Asia/Tokyo"}).format(date),items.length,items.filter(l=>l.result!=="担当者不在").length] as const});const max=Math.max(1,...data.map(x=>x[1]));return <><div className="flex h-[215px] items-end gap-2 border-b border-slate-200 bg-[repeating-linear-gradient(to_top,#fff_0,#fff_42px,#f1f4f8_43px)] px-2">{data.map(([d,a,b],i)=><div className="relative flex h-full flex-1 items-end gap-1" key={`${d}-${i}`}><i className="flex-1 rounded-t bg-blue-600" style={{height:`${Math.max(a?5:0,a/max*185)}px`}}/><i className="flex-1 rounded-t bg-blue-200" style={{height:`${Math.max(b?5:0,b/max*185)}px`}}/><label className="absolute -bottom-6 w-full text-center text-[10px] text-slate-500">{d}</label></div>)}</div><p className="mt-8 text-[10px] text-slate-500"><i className="mr-1 inline-block size-2 rounded-full bg-blue-600"/>架電数 <i className="ml-3 mr-1 inline-block size-2 rounded-full bg-blue-200"/>接続数</p></>}
function CardHead({title,sub,click}:{title:string;sub?:string;click?:()=>void}){return <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-extrabold">{title}</h2>{sub&&<button onClick={click} className={`text-[11px] ${click?"font-bold text-blue-600":"text-slate-500"}`}>{sub}</button>}</div>}

function Companies({companies,callCompany,add,bulkImport}:{companies:Company[];callCompany:(c:Company)=>void;add:()=>void;bulkImport:()=>void}) { const [q,setQ]=useState("");const [heat,setHeat]=useState("");const filtered=companies.filter(c=>(c.name+c.contact_name+c.phone+(c.website_url||"")).toLowerCase().includes(q.toLowerCase())&&(!heat||c.heat===heat));return <div className="fade-in"><div className="mb-3 flex flex-wrap gap-2"><div className="relative min-w-[240px] flex-1 md:max-w-sm"><Search className="absolute left-3 top-2.5 size-4 text-slate-400"/><input className="input pl-9" placeholder="企業名・担当者名・電話・URLで検索" value={q} onChange={e=>setQ(e.target.value)}/></div><select className="input !w-auto" value={heat} onChange={e=>setHeat(e.target.value)}><option value="">すべての温度感</option><option>高</option><option>中</option><option>低</option></select><button className="btn btn-light" onClick={bulkImport}><Upload size={15}/>リスト自動取り込み</button><button className="btn btn-primary" onClick={add}><Plus size={15}/>企業を追加</button></div><div className="card overflow-x-auto"><table className="w-full min-w-[1040px] border-collapse"><thead><tr className="bg-slate-50 text-left text-[10px] text-slate-500">{["企業名","URL","業種","担当者","温度感","最終架電","次回対応","担当",""].map(x=><th className="border-b border-slate-200 px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(c=><tr key={c.id} className="text-xs hover:bg-slate-50"><td className="border-b border-slate-100 p-4"><b>{c.name}</b><small className="mt-1 block text-[10px] text-slate-500">{c.location} ／ {c.phone}</small></td><td className="border-b border-slate-100 p-4">{c.website_url?<a className="inline-flex items-center gap-1 font-bold text-blue-600" href={c.website_url} target="_blank" rel="noreferrer">確認<ExternalLink size={12}/></a>:<a className="text-slate-400 underline" href={searchUrl(c.name)} target="_blank" rel="noreferrer">検索</a>}</td><td className="border-b border-slate-100 p-4">{c.industry}</td><td className="border-b border-slate-100 p-4">{c.contact_department} {c.contact_name}</td><td className="border-b border-slate-100 p-4"><HeatBadge heat={c.heat}/></td><td className="border-b border-slate-100 p-4">{fmt(c.last_called_at)}</td><td className="border-b border-slate-100 p-4">{fmt(c.next_action_at,true)}</td><td className="border-b border-slate-100 p-4">{c.owner_name}</td><td className="border-b border-slate-100 p-4"><button className="font-bold text-blue-600" onClick={()=>callCompany(c)}>架電する</button></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-16 text-center text-sm text-slate-500">該当する企業がありません</p>}</div></div> }
function HeatBadge({heat}:{heat:Heat}) {return <span className={`badge ${heat==="高"?"bg-red-50 text-red-600":heat==="中"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600"}`}>● {heat}</span>}

function CallScreen({company,member,next,onSaved,notify}:{company?:Company;member:string;next:()=>void;onSaved:()=>Promise<void>;notify:(s:string)=>void}) { const [staged]=useState<(TranscriptAnalysis&{transcript?:string})|null>(()=>{if(typeof window==="undefined")return null;const raw=sessionStorage.getItem("callflow_analysis");if(!raw)return null;sessionStorage.removeItem("callflow_analysis");try{return JSON.parse(raw) as TranscriptAnalysis&{transcript?:string}}catch{return null}});const [result,setResult]=useState<CallResult|"">(staged?.result||"");const [note,setNote]=useState(staged?`${staged.summary}\n次回対応：${staged.next_action}`:"");const [nextAt,setNextAt]=useState(staged?.next_action_at||"");const [saving,setSaving]=useState(false);if(!company)return <div className="card p-16 text-center text-slate-500">架電対象の企業がありません</div>;
 const save=async()=>{if(!result)return notify("架電結果を選択してください");setSaving(true);const created=new Date().toISOString(),updated={...company,heat:result==="アポ獲得"?"高" as Heat:company.heat,memo:note||company.memo,last_called_at:created,next_action_at:nextAt||undefined};const log:CallLog={id:crypto.randomUUID(),company_id:company.id,company_name:company.name,caller_name:member,result,note:note||"メモなし",transcript:staged?.transcript,ai_summary:staged?.summary,created_at:created,next_action_at:nextAt||undefined};try{await saveCallLog(log,updated);await onSaved();notify("架電記録を保存しました");setResult("");setNote("");setNextAt("");next()}catch(e){notify(e instanceof Error?e.message:"保存に失敗しました")}finally{setSaving(false)}};
 return <div className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><div className="card p-5"><div className="flex items-start justify-between gap-3"><div><HeatBadge heat={company.heat}/><h2 className="mt-2 text-2xl font-extrabold">{company.name}</h2><p className="mt-1 text-xs text-slate-500">{company.industry} ／ {company.location}</p><a href={`tel:${company.phone}`} className="mt-4 block text-xl font-extrabold text-blue-600">{company.phone}</a><div className="mt-3 flex flex-wrap gap-2">{company.website_url&&<a className="btn btn-light !py-2 text-xs" href={company.website_url} target="_blank" rel="noreferrer"><ExternalLink size={14}/>公式URLを開く</a>}<a className="btn btn-light !py-2 text-xs" href={searchUrl(company.name)} target="_blank" rel="noreferrer"><Search size={14}/>会社名で検索</a>{company.source_url&&<a className="btn btn-light !py-2 text-xs" href={company.source_url} target="_blank" rel="noreferrer">取得元</a>}</div></div><button className="btn btn-light" onClick={next}>次の企業 <ChevronRight size={15}/></button></div><div className="my-5 grid grid-cols-2 gap-2"><Info l="担当者" v={`${company.contact_department||""} ${company.contact_name}`}/><Info l="過去の接触" v={company.last_called_at?`最終 ${fmt(company.last_called_at,true)}`:"接触履歴なし"}/><Info l="前回の内容" v={company.memo||"記録なし"}/><Info l="次回対応" v={fmt(company.next_action_at,true)}/></div><PreCallChecklist company={company}/><div className="mt-4 rounded-r-lg border-l-[3px] border-blue-600 bg-slate-50 p-4 text-xs leading-7"><b>受付：</b>お世話になります。OLTLの辻と申します。<br/><em className="font-bold not-italic text-blue-600">県内大学生との接点づくりに関する採用広報のご提案</em>で、新卒採用のご担当者様をお願いできますか？<br/><br/><b>担当者：</b>県内学生に御社を知ってもらうためのSNS採用広報について、事例を交えて15分ほどご紹介しています。</div></div><div className="card"><CardHead title="架電結果を記録" sub={`担当：${member}`}/><div className="p-5"><div className="mb-4 rounded-xl border border-violet-200 bg-gradient-to-br from-violet-50 to-blue-50 p-3"><b className="block text-xs text-violet-700">✦ appserver解析で自動入力できます</b><span className="text-[10px] text-slate-500">右上の「文字起こし解析」を利用してください。外部AI APIなしでもルール解析で動作します。</span></div><Label text="架電結果"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-2 2xl:grid-cols-3">{results.map(r=><button key={r.value} onClick={()=>setResult(r.value)} className={`rounded-lg border p-2.5 text-[11px] ${result===r.value?"border-blue-500 bg-blue-50 font-bold text-blue-600":"border-slate-200 hover:border-blue-300"}`}>{r.label}</button>)}</div></Label><Label text="会話メモ"><textarea className="input min-h-24 resize-y" value={note} onChange={e=>setNote(e.target.value)} placeholder="相手の反応、課題、伝えた内容など"/></Label><Label text="次回対応日"><input type="datetime-local" className="input" value={nextAt} onChange={e=>setNextAt(e.target.value)}/></Label><div className="mt-4 flex gap-2"><button className="btn btn-light flex-1" onClick={next}>スキップ</button><button disabled={saving} className="btn btn-primary flex-1 disabled:opacity-50" onClick={save}>{saving?"保存中…":"記録して次へ"}</button></div></div></div></div> }
function Info({l,v}:{l:string;v:string}){return <div className="rounded-lg bg-slate-50 p-3"><small className="block text-[9px] text-slate-500">{l}</small><b className="mt-1 block text-xs">{v}</b></div>}
function Label({text,children}:{text:string;children:React.ReactNode}){return <label className="mb-4 block"><span className="mb-1.5 block text-[10px] font-bold text-slate-500">{text}</span>{children}</label>}

function searchUrl(name:string){return `https://www.google.com/search?q=${encodeURIComponent(`${name} 公式`)}`}
function normalizeUrl(url:string){if(!url)return "";return /^https?:\/\//i.test(url)?url:`https://${url}`}
function guessIndustry(text:string){const t=text.toLowerCase();if(/it|システム|saas|ソフト|開発/.test(t))return "IT・システム";if(/建設|工事|土木|設備/.test(t))return "建設・設備";if(/食品|飲食|製造|工場/.test(t))return "製造・食品";if(/病院|介護|福祉|医療/.test(t))return "医療・福祉";if(/ホテル|旅館|観光|宿泊/.test(t))return "観光・宿泊";return ""}
function parseLeadRows(raw:string, member:string, existing:Company[], defaults:{industry:string;location:string;source:string}) {
 const seen=new Set(existing.map(c=>`${c.name}|${c.phone}`));const phone=/0\d{1,4}[-(]?\d{1,4}[-)]?\d{3,4}/;const url=/(https?:\/\/[^\s,，\t]+|(?:www\.)?[a-z0-9-]+(?:\.[a-z0-9-]+)+(?:\/[^\s,，\t]*)?)/i;
 return raw.split(/\n+/).map(line=>line.trim()).filter(Boolean).map(line=>{const cols=line.split(/\t|,|，/).map(c=>c.trim()).filter(Boolean);const joined=cols.join(" ");const phoneMatch=joined.match(phone)?.[0]||"";const urlMatch=joined.match(url)?.[0]||"";const name=(cols.find(c=>!phone.test(c)&&!url.test(c)&&/(株式会社|有限会社|合同会社|Inc\.|Co\.|会社|法人|医院|病院|工業|商事|建設|食品|テック|デザイン)/i.test(c))||cols.find(c=>!phone.test(c)&&!url.test(c))||"").replace(/^"+|"+$/g,"");if(!name||!phoneMatch)return null;const key=`${name}|${phoneMatch}`;if(seen.has(key))return null;seen.add(key);return {id:crypto.randomUUID(),name,phone:phoneMatch,website_url:normalizeUrl(urlMatch),source_url:normalizeUrl(defaults.source),list_source:defaults.source?"貼り付けリスト":"手動取り込み",industry:defaults.industry||guessIndustry(joined),location:defaults.location,contact_name:"",contact_department:"",heat:"低" as Heat,owner_name:member,memo:"自動取り込みで登録"} as Company}).filter((x):x is Company=>Boolean(x));
}
function PreCallChecklist({company}:{company:Company}){return <div className="rounded-xl border border-blue-100 bg-blue-50/70 p-4"><b className="block text-xs text-blue-700">架電前チェック</b><div className="mt-2 grid gap-2 text-[11px] text-slate-600 sm:grid-cols-3"><span>1. 公式URLで事業内容を確認</span><span>2. 採用・ニュース欄を見る</span><span>3. 担当者名と前回メモを確認</span></div><p className="mt-2 text-[10px] text-slate-500">取得元：{company.list_source||"未設定"}{company.website_url?" ／ URL登録済み":" ／ 公式URL未登録"}</p></div>}

function HistoryView({logs}:{logs:CallLog[]}) {const [q,setQ]=useState("");const [f,setF]=useState("");const shown=logs.filter(l=>(l.company_name+l.note).toLowerCase().includes(q.toLowerCase())&&(!f||l.result===f));return <div><div className="mb-3 flex gap-2"><div className="relative flex-1 md:max-w-sm"><Search className="absolute left-3 top-2.5 size-4 text-slate-400"/><input className="input pl-9" value={q} onChange={e=>setQ(e.target.value)} placeholder="企業名・内容で検索"/></div><select className="input !w-auto" value={f} onChange={e=>setF(e.target.value)}><option value="">すべての結果</option>{results.slice(0,5).map(r=><option key={r.value}>{r.value}</option>)}</select></div><div className="card overflow-x-auto"><table className="w-full min-w-[850px]"><thead><tr className="bg-slate-50 text-left text-[10px] text-slate-500">{["日時","企業名","結果","担当","会話メモ・AI要約","次回対応"].map(x=><th key={x} className="border-b border-slate-200 p-3">{x}</th>)}</tr></thead><tbody>{shown.map(l=><tr className="text-xs" key={l.id}><td className="border-b border-slate-100 p-4">{fmt(l.created_at,true)}</td><td className="border-b border-slate-100 p-4 font-bold">{l.company_name}</td><td className="border-b border-slate-100 p-4"><span className={`badge ${badge(l.result)}`}>{l.result}</span></td><td className="border-b border-slate-100 p-4">{l.caller_name}</td><td className="max-w-[360px] border-b border-slate-100 p-4">{l.ai_summary||l.note}</td><td className="border-b border-slate-100 p-4">{fmt(l.next_action_at,true)}</td></tr>)}</tbody></table></div></div>}
function Team({logs,members}:{logs:CallLog[];members:string[]}) {const data=useMemo(()=>members.map(name=>{const own=logs.filter(l=>l.caller_name===name);return {name,calls:own.length,appt:own.filter(l=>l.result==="アポ獲得").length}}).sort((a,b)=>b.calls-a.calls),[logs,members]);const connection=logs.length?Math.round(logs.filter(l=>l.result!=="担当者不在").length/logs.length*100):0;return <div><div className="grid grid-cols-2 gap-3 md:grid-cols-3"><Kpi l="チーム架電数" v={logs.length}/><Kpi l="チームアポ数" v={logs.filter(l=>l.result==="アポ獲得").length}/><Kpi l="平均接続率" v={`${connection}%`}/></div><div className="card mt-4"><CardHead title="メンバー実績" sub="直近500件"/><div className="p-5">{data.map((r,i)=><div key={r.name} className="grid grid-cols-[30px_1fr_65px_65px] items-center gap-3 border-b border-slate-100 py-3"><b className={i===0?"text-amber-500":"text-slate-400"}>{i+1}</b><div><b className="text-xs">{r.name}</b><div className="mt-1.5 h-1.5 overflow-hidden rounded bg-slate-100"><i className="block h-full rounded bg-blue-600" style={{width:`${Math.max(8,r.calls/Math.max(1,data[0]?.calls||1)*100)}%`}}/></div></div><p className="text-right text-sm font-bold">{r.calls}<small className="block text-[9px] font-normal text-slate-500">架電</small></p><p className="text-right text-sm font-bold">{r.appt}<small className="block text-[9px] font-normal text-slate-500">アポ</small></p></div>)}</div></div></div>}
function Kpi({l,v}:{l:string;v:string|number}){return <div className="card p-4"><small className="font-bold text-slate-500">{l}</small><p className="mt-2 text-3xl font-extrabold">{v}</p></div>}

function Modal({title,sub,close,children}:{title:string;sub?:string;close:()=>void;children:React.ReactNode}) {return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-3" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="max-h-[94vh] w-full max-w-[680px] overflow-auto rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 p-5"><div><h2 className="font-extrabold">{title}</h2>{sub&&<p className="mt-1 text-[10px] text-slate-500">{sub}</p>}</div><button onClick={close}><X className="size-5 text-slate-400"/></button></div><div className="p-5">{children}</div></div></div>}
function LeadImportModal({member,existing,close,saved}:{member:string;existing:Company[];close:()=>void;saved:(added:number)=>void}) {const [raw,setRaw]=useState("株式会社サンプル商事,076-000-0000,https://example.com\n石川採用テック 076-111-2222 www.example.jp");const [defaults,setDefaults]=useState({industry:"",location:"石川県",source:""});const [busy,setBusy]=useState(false);const leads=useMemo(()=>parseLeadRows(raw,member,existing,defaults),[raw,member,existing,defaults]);const submit=async()=>{if(!leads.length)return;setBusy(true);try{for(const lead of leads)await saveCompany(lead);saved(leads.length)}finally{setBusy(false)}};return <Modal title="営業先リストを自動取り込み" sub="CSV・表・Webページからコピーしたテキストを貼ると、会社名・電話番号・URLを抽出します" close={close}><div className="grid gap-3 sm:grid-cols-3"><Field l="既定の業種" v={defaults.industry} set={v=>setDefaults(d=>({...d,industry:v}))}/><Field l="既定の所在地" v={defaults.location} set={v=>setDefaults(d=>({...d,location:v}))}/><Field l="取得元URL" v={defaults.source} set={v=>setDefaults(d=>({...d,source:v}))}/></div><Label text="リスト貼り付け"><textarea className="input min-h-[180px] resize-y font-mono text-xs" value={raw} onChange={e=>setRaw(e.target.value)} placeholder="会社名, 電話番号, URL の順でなくてもOKです"/></Label><div className="mb-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><b className="block text-slate-800">取り込み候補：{leads.length}件</b><p className="mt-1 text-[10px]">既存の企業名＋電話番号と重複する行、会社名か電話番号が取れない行は除外します。</p></div>{leads.length>0&&<div className="mb-4 max-h-44 overflow-auto rounded-xl border border-slate-100"><table className="w-full text-left text-[11px]"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-2">企業名</th><th className="p-2">電話</th><th className="p-2">URL</th></tr></thead><tbody>{leads.slice(0,20).map(l=><tr key={l.id}><td className="border-t border-slate-100 p-2 font-bold">{l.name}</td><td className="border-t border-slate-100 p-2">{l.phone}</td><td className="border-t border-slate-100 p-2">{l.website_url||"未検出"}</td></tr>)}</tbody></table></div>}<button disabled={busy||!leads.length} onClick={submit} className="btn btn-primary w-full disabled:opacity-50">{busy?"取り込み中…":`${leads.length}件を登録する`}</button></Modal>}
function CompanyModal({member,close,saved}:{member:string;close:()=>void;saved:(c:Company)=>void}) {const [form,setForm]=useState({name:"",phone:"",website_url:"",source_url:"",industry:"",location:"石川県",contact_name:"",contact_department:"",heat:"低" as Heat,memo:""});const [busy,setBusy]=useState(false);const change=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));const submit=async()=>{if(!form.name||!form.phone)return;setBusy(true);try{const c=await saveCompany({id:crypto.randomUUID(),...form,website_url:normalizeUrl(form.website_url),source_url:normalizeUrl(form.source_url),owner_name:member});saved(c)}finally{setBusy(false)}};return <Modal title="企業を追加" close={close}><div className="grid gap-3 sm:grid-cols-2"><Field l="企業名 *" v={form.name} set={v=>change("name",v)}/><Field l="電話番号 *" v={form.phone} set={v=>change("phone",v)}/><Field l="公式URL" v={form.website_url} set={v=>change("website_url",v)}/><Field l="取得元URL" v={form.source_url} set={v=>change("source_url",v)}/><Field l="業種" v={form.industry} set={v=>change("industry",v)}/><Field l="所在地" v={form.location} set={v=>change("location",v)}/><Field l="担当者名" v={form.contact_name} set={v=>change("contact_name",v)}/><Field l="部署・役職" v={form.contact_department} set={v=>change("contact_department",v)}/><Label text="温度感"><select className="input" value={form.heat} onChange={e=>change("heat",e.target.value)}><option>低</option><option>中</option><option>高</option></select></Label><div className="sm:col-span-2"><Label text="メモ"><textarea className="input min-h-20" value={form.memo} onChange={e=>change("memo",e.target.value)}/></Label></div></div><button disabled={busy||!form.name||!form.phone} onClick={submit} className="btn btn-primary w-full disabled:opacity-50">{busy?"登録中…":"企業を登録する"}</button></Modal>}
function Field({l,v,set}:{l:string;v:string;set:(v:string)=>void}){return <Label text={l}><input className="input" value={v} onChange={e=>set(e.target.value)}/></Label>}
function TranscriptModal({company,close,onApply}:{company?:Company;close:()=>void;onApply:(a:TranscriptAnalysis,transcript:string)=>void}) {const [text,setText]=useState("");const [analysis,setAnalysis]=useState<TranscriptAnalysis|null>(null);const [busy,setBusy]=useState(false);const run=async()=>{if(text.trim().length<15)return;setBusy(true);try{const res=await fetch("/api/analyze-transcript",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({transcript:text,company_name:company?.name})});if(!res.ok)throw new Error("解析できませんでした");setAnalysis(await res.json())}finally{setBusy(false)}};return <Modal title="✦ 通話文字起こし解析" sub="外部AI APIなしでもappserver内のルール解析で、結果・要約・次回対応を整理します" close={close}><Label text="文字起こし"><textarea className="input min-h-[190px]" value={text} onChange={e=>setText(e.target.value)} placeholder="お世話になります、OLTLの辻と申します。採用広報の件で…"/></Label><button disabled={busy||text.length<15} onClick={run} className="btn btn-ai w-full disabled:opacity-50"><Sparkles size={15}/>{busy?"解析中…":"appserverで解析する"}</button>{analysis&&<div className="mt-4 border-t border-slate-100 pt-4"><div className="grid grid-cols-2 gap-2"><Analysis l="架電結果" v={analysis.result}/><Analysis l="温度感" v={analysis.heat}/><Analysis l="次回対応" v={analysis.next_action}/><Analysis l="検出した担当者" v={analysis.contact_name||"検出できず"}/></div><div className="mt-2 rounded-lg bg-violet-50 p-3 text-xs leading-6"><b className="block text-violet-700">解析要約</b>{analysis.summary}</div><p className="mt-2 text-right text-[9px] text-slate-400">解析信頼度 {Math.round(analysis.confidence*100)}%</p><button className="btn btn-primary mt-3 w-full" onClick={()=>onApply(analysis,text)}>架電記録に反映する</button></div>}</Modal>}
function Analysis({l,v}:{l:string;v:string}){return <div className="rounded-lg bg-slate-50 p-3"><small className="block text-[9px] text-slate-500">{l}</small><b className="mt-1 block text-xs">{v}</b></div>}
